name = "Labelyst"
uuid = "e3e22cc6-7a1b-468c-b496-76d63e0a57cd"
authors = ["emanuel-kopp <emanuel.kopp@outlook.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"
DataFrames = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
